# Generated by Django 2.1 on 2018-08-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='product',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='recipe',
        ),
    ]
