# Generated by Django 2.1 on 2018-08-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180822_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('i', 'in progress'), ('c', 'completed'), ('x', 'cancelled')], default='i', max_length=1),
        ),
    ]
