# Generated by Django 2.1 on 2018-08-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopifysku',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopify_skus', to='api.Team'),
            preserve_default=False,
        ),
    ]
