# Generated by Django 2.1 on 2018-09-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180828_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('rm', 'raw materials'), ('fg', 'finished goods')], default='rm', max_length=2),
        ),
    ]
