# Generated by Django 2.1 on 2018-09-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180904_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedinventory',
            name='message',
            field=models.CharField(blank=True, default='Received Inventory', max_length=200),
        ),
    ]
