# Generated by Django 2.1 on 2018-09-11 01:51

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_receivedinventory_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
