# Generated by Django 2.1 on 2018-09-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_receivedinventory_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifysku',
            name='channel',
            field=models.CharField(default='shopify', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='squarespace_access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
