# Generated by Django 2.1 on 2018-08-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180812_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchitem',
            name='active_recipe',
        ),
        migrations.RemoveField(
            model_name='batchitem',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='batchitem',
            name='product',
        ),
        migrations.AddField(
            model_name='batch',
            name='active_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='api.Recipe'),
        ),
        migrations.AddField(
            model_name='batch',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='api.Product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BatchItem',
        ),
    ]
