# Generated by Django 2.1 on 2018-08-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_shopifysku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysku',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopify_skus', to='api.Product'),
        ),
        migrations.AlterField(
            model_name='shopifysku',
            name='sku',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
