# Generated by Django 2.1 on 2018-08-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180814_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysku',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='shopifysku',
            name='variant_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shopifysku',
            name='variant_sku',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
