# Generated by Django 2.1 on 2018-08-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180815_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dollar_value',
        ),
        migrations.AddField(
            model_name='receivedinventory',
            name='dollar_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
