# Generated by Django 2.1 on 2018-08-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180822_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.CharField(default='manual', max_length=20),
        ),
    ]
