# Generated by Django 2.1 on 2018-08-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180823_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
