# Generated by Django 2.1 on 2018-08-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180823_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='calendar_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='calendar_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
